nav:
  Home: /
  About: /about/
  Blog: /blog/
  Projects: /projects/

projects_url: http://github.com/probberechts

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/boobo94
        twitter: https://twitter.com/militaru_bogdan
        facebook: https://www.facebook.com/bogdanalexandru.militaru
        linkedin: https://www.linkedin.com/in/bogdan-alexandru-militaru-bb801697/
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
